site_name: lernOS Podcasting Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen:
        - Grundlagen: 2-0-Grundlagen.md
        - Podcasting-Canvas: 2-1-Podcasting-Canvas.md
        - Format: 2-2-Format.md
        - Workflow: 2-3-Workflow.md
        - Hardare:
            Überblick: 2-4-0-Hardware.md
            Mikrofone und Headsets: 2-4-1-Mikrofone-Headsets.md
            Audio-Rekorder: 2-4-2-Audio-Rekorder.md
            Audio-Interfaces und Mischpulte: 2-4-3-Audio-Interfaces-Mischpulte.md
            Audio-Processing: 2-4-4-Audio-Processing.md
        - Software:
            Überlick: 2-5-0-Software.md
            Ardour: 2-5-1-Ardour.md
            Audacity: 2-5-2-Audacity.md
            Audition: 2-5-3-Audition.md
            Ferrite: 2-5-4-Ferrite.md
            Garageband: 2-5-5-Garageband.md
            Hindenburg: 2-5-6-Hindenburg.md
            Reaper und Ultraschall: 2-5-7-Reaper-Ultraschall.md
            Studio Link: 2-5-8-Studio-Link.md
            Zencastr: 2-5-9-Zencastr.md
        - Studio: 2-6-Studio.md
        - Literatur und Links: 2-7-Literatur-Links.md
    - Lernpfad:
            Überblick: 3-0-Lernpfad.md
            Get Started (Kata): 3-1-Kata-Get-Started.md
            Wähle eine Podcast App und finde Podcasts (Kata): 3-2-Kata-Podcast-Beispiele.md
            Nutze den Podcast Canvas als Checkliste (Kata): 3-3-Kata-Podcast-Canvas.md
            Nimm deine "Nullnummer" auf (Kata): 3-4-Kata-Nullnummer.md
            Dein Podcast-Studio (Kata): 3-5-Kata-Podcast-Studio.md
            Achtung Aufnahme Episode 1 (Kata): 3-6-Kata-Episode-1.md
            Deine Podcast-Webseite (Kata): 3-7-Kata-Podcast-Webseite.md
            Achtung Aufnahme Episode 2 (Kata): 3-8-Kata-Episode-2.md
            Publiziere deine Episoden (Kata): 3-9-Kata-Publikation.md
            Kommunikation, Kommunikation, Kommunikation (Kata): 3-10-Kata-Kommunikation.md
            Podcast-Klinik (Kata): 3-11-Kata-Podcast-Klinik.md
    - Anhang: 4-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-podcasting/blob/master/de/lernOS-Podcasting-Guide-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-podcasting/blob/master/de/lernOS-Podcasting-Guide-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-podcasting/blob/master/de/lernOS-Podcasting-Guide-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-podcasting/blob/master/de/lernOS-Podcasting-Guide-de.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-podcasting/blob/master/de/lernOS-Podcasting-Guide-de.mobi
    - Links:
      - Präsentation: https://cogneon.github.io/lernos-podcasting/de-slides
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: material
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-podcasting'
repo_url: 'https://github.com/cogneon/lernos-podcasting'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search