site_name: lernOS Podcasting Leitfaden
site_url: https://cogneon.github.io/

docs_dir: src

site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen:
        - Grundlagen: 2-0-Grundlagen.md
        - Podcasting-Canvas: 2-1-Podcasting-Canvas.md
        - Format: 2-2-Format.md
        - Workflow: 2-3-Workflow.md
        - Technik: 2-4-Hardware.md
        - Software: 2-5-Software.md
        - Studio: 2-6-Studio.md
        - Literatur und Links: 2-7-Literatur-Links.md
    - Lernpfad: 3-Lernpfad.md
    - Anhang: 4-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-podcasting'
repo_url: 'https://github.com/cogneon/lernos-podcasting'

google_analytics:
  - 'UA-156969141-1'
  - 'auto'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/lern_os'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/showcase/lern-os'
        - type: 'github'
          link: 'https://github.com/cogneon'
    disqus: lernos
