site_name: lernOS Podcasting Leitfaden

docs_dir: src

site_dir: ../docs/de

nav:
    - Vorwort: 1-Vorwort.md
    - Lizenz: 2-Lizenz.md
    - Grundlagen:
        - Grundlagen: 3-0-Grundlagen.md
        - Format: 3-1-Format.md
        - Workflow: 3-2-Workflow.md
        - Technik: 3-3-Technik.md
        - Software: 3-4-Software.md
        - Studio: 3-5-Studio.md
        - Literatur und Links: 3-6-Literatur-Links.md
    - Lernpfad: 4-Lernpfad.md
    - Stop talking: 5-Stop-talking.md
    - Anhang: 6-Anhang.md

theme: readthedocs
