site_name: lernOS Podcasting Leitfaden
site_url: https://cogneon.github.io/lernos-podcasting/

docs_dir: src

site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen:
        - Grundlagen: 2-0-Grundlagen.md
        - Format: 2-1-Format.md
        - Workflow: 2-2-Workflow.md
        - Technik: 2-3-Technik.md
        - Software: 2-4-Software.md
        - Studio: 2-5-Studio.md
        - Literatur und Links: 2-6-Literatur-Links.md
    - Lernpfad: 3-Lernpfad.md
    - Anhang: 4-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-podcasting'
repo_url: 'https://github.com/cogneon/lernos-podcasting'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/lern_os'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/showcase/lern-os'
        - type: 'github'
          link: 'https://github.com/cogneon'
    disqus: lernos
